v 1 START
v 2 Confirmationofreceipt
v 3 T02Checkconfirmationofreceipt
v 4 T04Determineconfirmationofreceipt
v 5 T05Printandsendconfirmationofreceipt
v 6 T06Determinenecessityofstopadvice
v 7 T10Determinenecessitytostopindication
v 8 T16Reportreasonstoholdrequest
v 9 T17CheckreportYtostopindication
v 10 T18AdjustreportYtostopindicition
v 11 T17CheckreportYtostopindication
v 12 T18AdjustreportYtostopindicition
v 13 T17CheckreportYtostopindication
v 14 T19DeterminereportYtostopindication
v 15 T20PrintreportYtostopindication
v 16 END
e 1 2  START__Confirmationofreceipt
e 2 3  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 4  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 3 8  T02Checkconfirmationofreceipt__T16Reportreasonstoholdrequest
e 4 6  T04Determineconfirmationofreceipt__T06Determinenecessityofstopadvice
e 5 6  T05Printandsendconfirmationofreceipt__T06Determinenecessityofstopadvice
e 6 7  T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
e 7 16  T10Determinenecessitytostopindication__END
e 8 9  T16Reportreasonstoholdrequest__T17CheckreportYtostopindication
e 8 11  T16Reportreasonstoholdrequest__T17CheckreportYtostopindication
e 8 13  T16Reportreasonstoholdrequest__T17CheckreportYtostopindication
e 13 14  T17CheckreportYtostopindication__T19DeterminereportYtostopindication
e 14 15  T19DeterminereportYtostopindication__T20PrintreportYtostopindication
e 10 14  T18AdjustreportYtostopindicition__T19DeterminereportYtostopindication
e 9 10  T17CheckreportYtostopindication__T18AdjustreportYtostopindicition
e 12 14  T18AdjustreportYtostopindicition__T19DeterminereportYtostopindication
e 11 12  T17CheckreportYtostopindication__T18AdjustreportYtostopindicition
