v 1 START
v 2 Confirmationofreceipt
v 3 T06Determinenecessityofstopadvice
v 4 T02Checkconfirmationofreceipt
v 5 T04Determineconfirmationofreceipt
v 6 T10Determinenecessitytostopindication
v 7 T05Printandsendconfirmationofreceipt
v 8 T11CreatedocumentXrequestunlicensed
v 9 T12CheckdocumentXrequestunlicensed
v 10 T14DeterminedocumentXrequestunlicensed
v 11 T15PrintdocumentXrequestunlicensed
v 12 END
e 1 2  START__Confirmationofreceipt
e 2 4  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 4  T06Determinenecessityofstopadvice__T02Checkconfirmationofreceipt
e 4 5  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 5 6  T04Determineconfirmationofreceipt__T10Determinenecessitytostopindication
e 6 7  T10Determinenecessitytostopindication__T05Printandsendconfirmationofreceipt
e 6 9  T10Determinenecessitytostopindication__T12CheckdocumentXrequestunlicensed
e 9 10  T12CheckdocumentXrequestunlicensed__T14DeterminedocumentXrequestunlicensed
e 10 11  T14DeterminedocumentXrequestunlicensed__T15PrintdocumentXrequestunlicensed
e 11 12  T15PrintdocumentXrequestunlicensed__END
e 8 10  T11CreatedocumentXrequestunlicensed__T14DeterminedocumentXrequestunlicensed
e 7 8  T05Printandsendconfirmationofreceipt__T11CreatedocumentXrequestunlicensed
