v 1 SUB_2
v 2 T05Printandsendconfirmationofreceipt
v 3 T06Determinenecessityofstopadvice
v 4 T10Determinenecessitytostopindication
v 5 T16Reportreasonstoholdrequest
v 6 T17CheckreportYtostopindication
v 7 T18AdjustreportYtostopindicition
v 8 T17CheckreportYtostopindication
v 9 T18AdjustreportYtostopindicition
v 10 T17CheckreportYtostopindication
v 11 T19DeterminereportYtostopindication
v 12 T20PrintreportYtostopindication
v 13 END
d 1 5 T02Checkconfirmationofreceipt__T16Reportreasonstoholdrequest
d 1 3 T04Determineconfirmationofreceipt__T06Determinenecessityofstopadvice
d 2 3 T05Printandsendconfirmationofreceipt__T06Determinenecessityofstopadvice
d 3 4 T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
d 4 13 T10Determinenecessitytostopindication__END
d 5 6 T16Reportreasonstoholdrequest__T17CheckreportYtostopindication
d 5 8 T16Reportreasonstoholdrequest__T17CheckreportYtostopindication
d 5 10 T16Reportreasonstoholdrequest__T17CheckreportYtostopindication
d 10 11 T17CheckreportYtostopindication__T19DeterminereportYtostopindication
d 11 12 T19DeterminereportYtostopindication__T20PrintreportYtostopindication
d 7 11 T18AdjustreportYtostopindicition__T19DeterminereportYtostopindication
d 6 7 T17CheckreportYtostopindication__T18AdjustreportYtostopindicition
d 9 11 T18AdjustreportYtostopindicition__T19DeterminereportYtostopindication
d 8 9 T17CheckreportYtostopindication__T18AdjustreportYtostopindicition
