v 1 T10Determinenecessitytostopindication
v 2 T05Printandsendconfirmationofreceipt
v 3 T11CreatedocumentXrequestunlicensed
v 4 T12CheckdocumentXrequestunlicensed
v 5 T14DeterminedocumentXrequestunlicensed
v 6 T15PrintdocumentXrequestunlicensed
v 7 END
d 1 2 T10Determinenecessitytostopindication__T05Printandsendconfirmationofreceipt
d 1 4 T10Determinenecessitytostopindication__T12CheckdocumentXrequestunlicensed
d 4 5 T12CheckdocumentXrequestunlicensed__T14DeterminedocumentXrequestunlicensed
d 5 6 T14DeterminedocumentXrequestunlicensed__T15PrintdocumentXrequestunlicensed
d 6 7 T15PrintdocumentXrequestunlicensed__END
d 3 5 T11CreatedocumentXrequestunlicensed__T14DeterminedocumentXrequestunlicensed
d 2 3 T05Printandsendconfirmationofreceipt__T11CreatedocumentXrequestunlicensed
