v 1 START
v 2 Confirmationofreceipt
v 3 T02Checkconfirmationofreceipt
v 4 T04Determineconfirmationofreceipt
v 5 T05Printandsendconfirmationofreceipt
v 6 T06Determinenecessityofstopadvice
v 7 T10Determinenecessitytostopindication
v 8 T11CreatedocumentXrequestunlicensed
v 9 T12CheckdocumentXrequestunlicensed
v 10 T14DeterminedocumentXrequestunlicensed
v 11 T15PrintdocumentXrequestunlicensed
v 12 END
d 1 2 START__Confirmationofreceipt
d 2 3 Confirmationofreceipt__T02Checkconfirmationofreceipt
d 3 4 T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
d 4 6 T04Determineconfirmationofreceipt__T06Determinenecessityofstopadvice
d 5 6 T05Printandsendconfirmationofreceipt__T06Determinenecessityofstopadvice
d 6 7 T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
d 9 10 T12CheckdocumentXrequestunlicensed__T14DeterminedocumentXrequestunlicensed
d 10 11 T14DeterminedocumentXrequestunlicensed__T15PrintdocumentXrequestunlicensed
d 11 12 T15PrintdocumentXrequestunlicensed__END
d 7 8 T10Determinenecessitytostopindication__T11CreatedocumentXrequestunlicensed
d 8 9 T11CreatedocumentXrequestunlicensed__T12CheckdocumentXrequestunlicensed
