v 1 START
v 2 Confirmationofreceipt
v 3 T06Determinenecessityofstopadvice
v 4 T10Determinenecessitytostopindication
v 5 T11CreatedocumentXrequestunlicensed
v 6 T12CheckdocumentXrequestunlicensed
v 7 T02Checkconfirmationofreceipt
v 8 T04Determineconfirmationofreceipt
v 9 T05Printandsendconfirmationofreceipt
v 10 T13AdjustdocumentXrequestunlicensed
v 11 T12CheckdocumentXrequestunlicensed
v 12 T14DeterminedocumentXrequestunlicensed
v 13 T15PrintdocumentXrequestunlicensed
v 14 END
e 1 2  START__Confirmationofreceipt
e 2 7  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 4  T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
e 6 7  T12CheckdocumentXrequestunlicensed__T02Checkconfirmationofreceipt
e 7 8  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 11 12  T12CheckdocumentXrequestunlicensed__T14DeterminedocumentXrequestunlicensed
e 12 13  T14DeterminedocumentXrequestunlicensed__T15PrintdocumentXrequestunlicensed
e 13 14  T15PrintdocumentXrequestunlicensed__END
e 4 5  T10Determinenecessitytostopindication__T11CreatedocumentXrequestunlicensed
e 5 6  T11CreatedocumentXrequestunlicensed__T12CheckdocumentXrequestunlicensed
e 5 9  T11CreatedocumentXrequestunlicensed__T05Printandsendconfirmationofreceipt
e 5 11  T11CreatedocumentXrequestunlicensed__T12CheckdocumentXrequestunlicensed
e 10 12  T13AdjustdocumentXrequestunlicensed__T14DeterminedocumentXrequestunlicensed
e 9 10  T05Printandsendconfirmationofreceipt__T13AdjustdocumentXrequestunlicensed

