XP
v 1 START
v 2 Confirmationofreceipt
v 3 T02Checkconfirmationofreceipt
v 4 T04Determineconfirmationofreceipt
v 5 T05Printandsendconfirmationofreceipt
v 6 T06Determinenecessityofstopadvice
v 7 T10Determinenecessitytostopindication
v 8 T11CreatedocumentXrequestunlicensed
v 9 T12CheckdocumentXrequestunlicensed
v 10 T14DeterminedocumentXrequestunlicensed
v 11 T15PrintdocumentXrequestunlicensed
v 12 END
e 1 2  START__Confirmationofreceipt
e 2 3  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 4  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 4 6  T04Determineconfirmationofreceipt__T06Determinenecessityofstopadvice
e 5 6  T05Printandsendconfirmationofreceipt__T06Determinenecessityofstopadvice
e 6 7  T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
e 9 10  T12CheckdocumentXrequestunlicensed__T14DeterminedocumentXrequestunlicensed
e 10 11  T14DeterminedocumentXrequestunlicensed__T15PrintdocumentXrequestunlicensed
e 11 12  T15PrintdocumentXrequestunlicensed__END
e 7 8  T10Determinenecessitytostopindication__T11CreatedocumentXrequestunlicensed
e 8 9  T11CreatedocumentXrequestunlicensed__T12CheckdocumentXrequestunlicensed

XP
v 1 START
v 2 Confirmationofreceipt
v 3 T02Checkconfirmationofreceipt
v 4 T04Determineconfirmationofreceipt
v 5 T05Printandsendconfirmationofreceipt
v 6 T06Determinenecessityofstopadvice
v 7 T10Determinenecessitytostopindication
v 8 T11CreatedocumentXrequestunlicensed
v 9 END
e 1 2  START__Confirmationofreceipt
e 2 3  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 4  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 4 6  T04Determineconfirmationofreceipt__T06Determinenecessityofstopadvice
e 5 6  T05Printandsendconfirmationofreceipt__T06Determinenecessityofstopadvice
e 6 7  T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
e 7 8  T10Determinenecessitytostopindication__T11CreatedocumentXrequestunlicensed
e 8 9  T11CreatedocumentXrequestunlicensed__END

XP
v 1 START
v 2 Confirmationofreceipt
v 3 T02Checkconfirmationofreceipt
v 4 T04Determineconfirmationofreceipt
v 5 T05Printandsendconfirmationofreceipt
v 6 T06Determinenecessityofstopadvice
v 7 T10Determinenecessitytostopindication
v 8 T11CreatedocumentXrequestunlicensed
v 9 T12CheckdocumentXrequestunlicensed
v 10 T14DeterminedocumentXrequestunlicensed
v 11 T15PrintdocumentXrequestunlicensed
v 12 END
e 1 2  START__Confirmationofreceipt
e 2 3  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 4  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 4 6  T04Determineconfirmationofreceipt__T06Determinenecessityofstopadvice
e 5 6  T05Printandsendconfirmationofreceipt__T06Determinenecessityofstopadvice
e 6 7  T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
e 9 10  T12CheckdocumentXrequestunlicensed__T14DeterminedocumentXrequestunlicensed
e 10 11  T14DeterminedocumentXrequestunlicensed__T15PrintdocumentXrequestunlicensed
e 11 12  T15PrintdocumentXrequestunlicensed__END
e 7 8  T10Determinenecessitytostopindication__T11CreatedocumentXrequestunlicensed
e 8 9  T11CreatedocumentXrequestunlicensed__T12CheckdocumentXrequestunlicensed

XP
v 1 START
v 2 Confirmationofreceipt
v 3 T06Determinenecessityofstopadvice
v 4 T07-3Draftinternadviceholdforaspect3
v 5 T06Determinenecessityofstopadvice
v 6 T10Determinenecessitytostopindication
v 7 T02Checkconfirmationofreceipt
v 8 T04Determineconfirmationofreceipt
v 9 T05Printandsendconfirmationofreceipt
v 10 END
e 1 2  START__Confirmationofreceipt
e 2 7  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 5 6  T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
e 6 7  T10Determinenecessitytostopindication__T02Checkconfirmationofreceipt
e 6 9  T10Determinenecessitytostopindication__T05Printandsendconfirmationofreceipt
e 7 8  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 9 10  T05Printandsendconfirmationofreceipt__END
e 3 4  T06Determinenecessityofstopadvice__T07-3Draftinternadviceholdforaspect3
e 4 5  T07-3Draftinternadviceholdforaspect3__T06Determinenecessityofstopadvice

XP
v 1 START
v 2 Confirmationofreceipt
v 3 T06Determinenecessityofstopadvice
v 4 T07-5Draftinternadviceaspect5
v 5 T07-1Draftinternadviceaspect1
v 6 T08Draftandsendrequestforadvice
v 7 T09-1Processorreceiveexternaladvicefromparty1
v 8 T07-3Draftinternadviceholdforaspect3
v 9 T07-4Draftinternaladvicetoholdfortype4
v 10 T07-2Draftinternadviceaspect2
v 11 T02Checkconfirmationofreceipt
v 12 T04Determineconfirmationofreceipt
v 13 T05Printandsendconfirmationofreceipt
v 14 T06Determinenecessityofstopadvice
v 15 T10Determinenecessitytostopindication
v 16 END
e 1 2  START__Confirmationofreceipt
e 2 11  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 4  T06Determinenecessityofstopadvice__T07-5Draftinternadviceaspect5
e 3 5  T06Determinenecessityofstopadvice__T07-1Draftinternadviceaspect1
e 5 6  T07-1Draftinternadviceaspect1__T08Draftandsendrequestforadvice
e 5 11  T07-1Draftinternadviceaspect1__T02Checkconfirmationofreceipt
e 6 14  T08Draftandsendrequestforadvice__T06Determinenecessityofstopadvice
e 10 14  T07-2Draftinternadviceaspect2__T06Determinenecessityofstopadvice
e 11 12  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 12 14  T04Determineconfirmationofreceipt__T06Determinenecessityofstopadvice
e 13 14  T05Printandsendconfirmationofreceipt__T06Determinenecessityofstopadvice
e 14 15  T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
e 15 16  T10Determinenecessitytostopindication__END
e 4 8  T07-5Draftinternadviceaspect5__T07-3Draftinternadviceholdforaspect3
e 8 9  T07-3Draftinternadviceholdforaspect3__T07-4Draftinternaladvicetoholdfortype4

XP
v 1 START
v 2 Confirmationofreceipt
v 3 T06Determinenecessityofstopadvice
v 4 T10Determinenecessitytostopindication
v 5 T11CreatedocumentXrequestunlicensed
v 6 T12CheckdocumentXrequestunlicensed
v 7 T02Checkconfirmationofreceipt
v 8 T04Determineconfirmationofreceipt
v 9 T05Printandsendconfirmationofreceipt
v 10 T13AdjustdocumentXrequestunlicensed
v 11 END
e 1 2  START__Confirmationofreceipt
e 2 7  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 4  T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
e 6 7  T12CheckdocumentXrequestunlicensed__T02Checkconfirmationofreceipt
e 7 8  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 4 5  T10Determinenecessitytostopindication__T11CreatedocumentXrequestunlicensed
e 5 6  T11CreatedocumentXrequestunlicensed__T12CheckdocumentXrequestunlicensed
e 5 9  T11CreatedocumentXrequestunlicensed__T05Printandsendconfirmationofreceipt
e 9 10  T05Printandsendconfirmationofreceipt__T13AdjustdocumentXrequestunlicensed
e 10 11  T13AdjustdocumentXrequestunlicensed__END

XP
v 1 START
v 2 Confirmationofreceipt
v 3 T06Determinenecessityofstopadvice
v 4 T06Determinenecessityofstopadvice
v 5 T06Determinenecessityofstopadvice
v 6 T07-4Draftinternaladvicetoholdfortype4
v 7 T06Determinenecessityofstopadvice
v 8 T10Determinenecessitytostopindication
v 9 T02Checkconfirmationofreceipt
v 10 T04Determineconfirmationofreceipt
v 11 T05Printandsendconfirmationofreceipt
v 12 END
e 1 2  START__Confirmationofreceipt
e 2 9  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 4  T06Determinenecessityofstopadvice__T06Determinenecessityofstopadvice
e 4 5  T06Determinenecessityofstopadvice__T06Determinenecessityofstopadvice
e 7 8  T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
e 8 9  T10Determinenecessitytostopindication__T02Checkconfirmationofreceipt
e 8 11  T10Determinenecessitytostopindication__T05Printandsendconfirmationofreceipt
e 9 10  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 11 12  T05Printandsendconfirmationofreceipt__END
e 5 6  T06Determinenecessityofstopadvice__T07-4Draftinternaladvicetoholdfortype4
e 6 7  T07-4Draftinternaladvicetoholdfortype4__T06Determinenecessityofstopadvice

XP
v 1 START
v 2 Confirmationofreceipt
v 3 T06Determinenecessityofstopadvice
v 4 T10Determinenecessitytostopindication
v 5 T11CreatedocumentXrequestunlicensed
v 6 T12CheckdocumentXrequestunlicensed
v 7 T02Checkconfirmationofreceipt
v 8 T04Determineconfirmationofreceipt
v 9 T05Printandsendconfirmationofreceipt
v 10 T13AdjustdocumentXrequestunlicensed
v 11 T12CheckdocumentXrequestunlicensed
v 12 T14DeterminedocumentXrequestunlicensed
v 13 T15PrintdocumentXrequestunlicensed
v 14 END
e 1 2  START__Confirmationofreceipt
e 2 7  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 4  T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
e 6 7  T12CheckdocumentXrequestunlicensed__T02Checkconfirmationofreceipt
e 7 8  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 11 12  T12CheckdocumentXrequestunlicensed__T14DeterminedocumentXrequestunlicensed
e 12 13  T14DeterminedocumentXrequestunlicensed__T15PrintdocumentXrequestunlicensed
e 13 14  T15PrintdocumentXrequestunlicensed__END
e 4 5  T10Determinenecessitytostopindication__T11CreatedocumentXrequestunlicensed
e 5 6  T11CreatedocumentXrequestunlicensed__T12CheckdocumentXrequestunlicensed
e 5 9  T11CreatedocumentXrequestunlicensed__T05Printandsendconfirmationofreceipt
e 5 11  T11CreatedocumentXrequestunlicensed__T12CheckdocumentXrequestunlicensed
e 10 12  T13AdjustdocumentXrequestunlicensed__T14DeterminedocumentXrequestunlicensed
e 9 10  T05Printandsendconfirmationofreceipt__T13AdjustdocumentXrequestunlicensed

XP
v 1 START
v 2 Confirmationofreceipt
v 3 T02Checkconfirmationofreceipt
v 4 T04Determineconfirmationofreceipt
v 5 T06Determinenecessityofstopadvice
v 6 T10Determinenecessitytostopindication
v 7 T05Printandsendconfirmationofreceipt
v 8 T11CreatedocumentXrequestunlicensed
v 9 T12CheckdocumentXrequestunlicensed
v 10 T14DeterminedocumentXrequestunlicensed
v 11 T15PrintdocumentXrequestunlicensed
v 12 END
e 1 2  START__Confirmationofreceipt
e 2 3  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 4  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 4 5  T04Determineconfirmationofreceipt__T06Determinenecessityofstopadvice
e 5 6  T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
e 6 7  T10Determinenecessitytostopindication__T05Printandsendconfirmationofreceipt
e 6 9  T10Determinenecessitytostopindication__T12CheckdocumentXrequestunlicensed
e 9 10  T12CheckdocumentXrequestunlicensed__T14DeterminedocumentXrequestunlicensed
e 10 11  T14DeterminedocumentXrequestunlicensed__T15PrintdocumentXrequestunlicensed
e 11 12  T15PrintdocumentXrequestunlicensed__END
e 8 10  T11CreatedocumentXrequestunlicensed__T14DeterminedocumentXrequestunlicensed
e 7 8  T05Printandsendconfirmationofreceipt__T11CreatedocumentXrequestunlicensed

XP
v 1 START
v 2 Confirmationofreceipt
v 3 T02Checkconfirmationofreceipt
v 4 T04Determineconfirmationofreceipt
v 5 T05Printandsendconfirmationofreceipt
v 6 T06Determinenecessityofstopadvice
v 7 T07-1Draftinternadviceaspect1
v 8 T07-4Draftinternaladvicetoholdfortype4
v 9 T06Determinenecessityofstopadvice
v 10 T10Determinenecessitytostopindication
v 11 END
e 1 2  START__Confirmationofreceipt
e 2 3  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 4  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 4 6  T04Determineconfirmationofreceipt__T06Determinenecessityofstopadvice
e 5 6  T05Printandsendconfirmationofreceipt__T06Determinenecessityofstopadvice
e 6 7  T06Determinenecessityofstopadvice__T07-1Draftinternadviceaspect1
e 9 10  T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
e 10 11  T10Determinenecessitytostopindication__END
e 7 8  T07-1Draftinternadviceaspect1__T07-4Draftinternaladvicetoholdfortype4
e 8 9  T07-4Draftinternaladvicetoholdfortype4__T06Determinenecessityofstopadvice

XP
v 1 START
v 2 Confirmationofreceipt
v 3 T06Determinenecessityofstopadvice
v 4 T10Determinenecessitytostopindication
v 5 T02Checkconfirmationofreceipt
v 6 T04Determineconfirmationofreceipt
v 7 T05Printandsendconfirmationofreceipt
v 8 T11CreatedocumentXrequestunlicensed
v 9 T12CheckdocumentXrequestunlicensed
v 10 T14DeterminedocumentXrequestunlicensed
v 11 T15PrintdocumentXrequestunlicensed
v 12 END
e 1 2  START__Confirmationofreceipt
e 2 5  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 4  T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
e 4 5  T10Determinenecessitytostopindication__T02Checkconfirmationofreceipt
e 4 7  T10Determinenecessitytostopindication__T05Printandsendconfirmationofreceipt
e 4 9  T10Determinenecessitytostopindication__T12CheckdocumentXrequestunlicensed
e 5 6  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 9 10  T12CheckdocumentXrequestunlicensed__T14DeterminedocumentXrequestunlicensed
e 10 11  T14DeterminedocumentXrequestunlicensed__T15PrintdocumentXrequestunlicensed
e 11 12  T15PrintdocumentXrequestunlicensed__END
e 8 10  T11CreatedocumentXrequestunlicensed__T14DeterminedocumentXrequestunlicensed
e 7 8  T05Printandsendconfirmationofreceipt__T11CreatedocumentXrequestunlicensed

XP
v 1 START
v 2 Confirmationofreceipt
v 3 T02Checkconfirmationofreceipt
v 4 T04Determineconfirmationofreceipt
v 5 T05Printandsendconfirmationofreceipt
v 6 T06Determinenecessityofstopadvice
v 7 T07-3Draftinternadviceholdforaspect3
v 8 T07-2Draftinternadviceaspect2
v 9 T06Determinenecessityofstopadvice
v 10 T07-3Draftinternadviceholdforaspect3
v 11 T07-2Draftinternadviceaspect2
v 12 T06Determinenecessityofstopadvice
v 13 T07-3Draftinternadviceholdforaspect3
v 14 T07-2Draftinternadviceaspect2
v 15 T06Determinenecessityofstopadvice
v 16 T10Determinenecessitytostopindication
v 17 END
e 1 2  START__Confirmationofreceipt
e 2 3  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 4  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 4 6  T04Determineconfirmationofreceipt__T06Determinenecessityofstopadvice
e 5 6  T05Printandsendconfirmationofreceipt__T06Determinenecessityofstopadvice
e 8 9  T07-2Draftinternadviceaspect2__T06Determinenecessityofstopadvice
e 11 12  T07-2Draftinternadviceaspect2__T06Determinenecessityofstopadvice
e 14 15  T07-2Draftinternadviceaspect2__T06Determinenecessityofstopadvice
e 15 16  T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
e 16 17  T10Determinenecessitytostopindication__END
e 7 9  T07-3Draftinternadviceholdforaspect3__T06Determinenecessityofstopadvice
e 10 12  T07-3Draftinternadviceholdforaspect3__T06Determinenecessityofstopadvice
e 13 15  T07-3Draftinternadviceholdforaspect3__T06Determinenecessityofstopadvice

XP
v 1 START
v 2 Confirmationofreceipt
v 3 T02Checkconfirmationofreceipt
v 4 T04Determineconfirmationofreceipt
v 5 T06Determinenecessityofstopadvice
v 6 T10Determinenecessitytostopindication
v 7 T05Printandsendconfirmationofreceipt
v 8 T11CreatedocumentXrequestunlicensed
v 9 END
e 1 2  START__Confirmationofreceipt
e 2 3  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 4  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 4 5  T04Determineconfirmationofreceipt__T06Determinenecessityofstopadvice
e 5 6  T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
e 6 7  T10Determinenecessitytostopindication__T05Printandsendconfirmationofreceipt
e 7 8  T05Printandsendconfirmationofreceipt__T11CreatedocumentXrequestunlicensed
e 8 9  T11CreatedocumentXrequestunlicensed__END

XP
v 1 START
v 2 Confirmationofreceipt
v 3 T06Determinenecessityofstopadvice
v 4 T10Determinenecessitytostopindication
v 5 T02Checkconfirmationofreceipt
v 6 T04Determineconfirmationofreceipt
v 7 T05Printandsendconfirmationofreceipt
v 8 T11CreatedocumentXrequestunlicensed
v 9 END
e 1 2  START__Confirmationofreceipt
e 2 5  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 4  T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
e 4 5  T10Determinenecessitytostopindication__T02Checkconfirmationofreceipt
e 4 7  T10Determinenecessitytostopindication__T05Printandsendconfirmationofreceipt
e 5 6  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 7 8  T05Printandsendconfirmationofreceipt__T11CreatedocumentXrequestunlicensed
e 8 9  T11CreatedocumentXrequestunlicensed__END

XP
v 1 START
v 2 Confirmationofreceipt
v 3 T02Checkconfirmationofreceipt
v 4 T04Determineconfirmationofreceipt
v 5 T05Printandsendconfirmationofreceipt
v 6 T06Determinenecessityofstopadvice
v 7 T10Determinenecessitytostopindication
v 8 T11CreatedocumentXrequestunlicensed
v 9 T12CheckdocumentXrequestunlicensed
v 10 T14DeterminedocumentXrequestunlicensed
v 11 T15PrintdocumentXrequestunlicensed
v 12 END
e 1 2  START__Confirmationofreceipt
e 2 3  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 4  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 4 6  T04Determineconfirmationofreceipt__T06Determinenecessityofstopadvice
e 5 6  T05Printandsendconfirmationofreceipt__T06Determinenecessityofstopadvice
e 6 7  T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
e 9 10  T12CheckdocumentXrequestunlicensed__T14DeterminedocumentXrequestunlicensed
e 10 11  T14DeterminedocumentXrequestunlicensed__T15PrintdocumentXrequestunlicensed
e 11 12  T15PrintdocumentXrequestunlicensed__END
e 7 8  T10Determinenecessitytostopindication__T11CreatedocumentXrequestunlicensed
e 8 9  T11CreatedocumentXrequestunlicensed__T12CheckdocumentXrequestunlicensed

XP
v 1 START
v 2 Confirmationofreceipt
v 3 T02Checkconfirmationofreceipt
v 4 T06Determinenecessityofstopadvice
v 5 T10Determinenecessitytostopindication
v 6 T11CreatedocumentXrequestunlicensed
v 7 T12CheckdocumentXrequestunlicensed
v 8 T04Determineconfirmationofreceipt
v 9 T14DeterminedocumentXrequestunlicensed
v 10 T05Printandsendconfirmationofreceipt
v 11 T15PrintdocumentXrequestunlicensed
v 12 END
e 1 2  START__Confirmationofreceipt
e 2 3  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 8  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 4 5  T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
e 7 9  T12CheckdocumentXrequestunlicensed__T14DeterminedocumentXrequestunlicensed
e 9 11  T14DeterminedocumentXrequestunlicensed__T15PrintdocumentXrequestunlicensed
e 10 11  T05Printandsendconfirmationofreceipt__T15PrintdocumentXrequestunlicensed
e 11 12  T15PrintdocumentXrequestunlicensed__END
e 5 6  T10Determinenecessitytostopindication__T11CreatedocumentXrequestunlicensed
e 6 7  T11CreatedocumentXrequestunlicensed__T12CheckdocumentXrequestunlicensed
e 6 10  T11CreatedocumentXrequestunlicensed__T05Printandsendconfirmationofreceipt

XP
v 1 START
v 2 Confirmationofreceipt
v 3 T02Checkconfirmationofreceipt
v 4 T04Determineconfirmationofreceipt
v 5 T05Printandsendconfirmationofreceipt
v 6 T06Determinenecessityofstopadvice
v 7 T10Determinenecessitytostopindication
v 8 T11CreatedocumentXrequestunlicensed
v 9 T12CheckdocumentXrequestunlicensed
v 10 T14DeterminedocumentXrequestunlicensed
v 11 T15PrintdocumentXrequestunlicensed
v 12 END
e 1 2  START__Confirmationofreceipt
e 2 3  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 4  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 4 6  T04Determineconfirmationofreceipt__T06Determinenecessityofstopadvice
e 5 6  T05Printandsendconfirmationofreceipt__T06Determinenecessityofstopadvice
e 6 7  T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
e 9 10  T12CheckdocumentXrequestunlicensed__T14DeterminedocumentXrequestunlicensed
e 10 11  T14DeterminedocumentXrequestunlicensed__T15PrintdocumentXrequestunlicensed
e 11 12  T15PrintdocumentXrequestunlicensed__END
e 7 8  T10Determinenecessitytostopindication__T11CreatedocumentXrequestunlicensed
e 8 9  T11CreatedocumentXrequestunlicensed__T12CheckdocumentXrequestunlicensed

XP
v 1 START
v 2 Confirmationofreceipt
v 3 T02Checkconfirmationofreceipt
v 4 T04Determineconfirmationofreceipt
v 5 T05Printandsendconfirmationofreceipt
v 6 T06Determinenecessityofstopadvice
v 7 T10Determinenecessitytostopindication
v 8 T11CreatedocumentXrequestunlicensed
v 9 T12CheckdocumentXrequestunlicensed
v 10 T14DeterminedocumentXrequestunlicensed
v 11 T15PrintdocumentXrequestunlicensed
v 12 END
e 1 2  START__Confirmationofreceipt
e 2 3  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 4  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 4 6  T04Determineconfirmationofreceipt__T06Determinenecessityofstopadvice
e 5 6  T05Printandsendconfirmationofreceipt__T06Determinenecessityofstopadvice
e 6 7  T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
e 9 10  T12CheckdocumentXrequestunlicensed__T14DeterminedocumentXrequestunlicensed
e 10 11  T14DeterminedocumentXrequestunlicensed__T15PrintdocumentXrequestunlicensed
e 11 12  T15PrintdocumentXrequestunlicensed__END
e 7 8  T10Determinenecessitytostopindication__T11CreatedocumentXrequestunlicensed
e 8 9  T11CreatedocumentXrequestunlicensed__T12CheckdocumentXrequestunlicensed

XP
v 1 START
v 2 Confirmationofreceipt
v 3 T02Checkconfirmationofreceipt
v 4 T06Determinenecessityofstopadvice
v 5 T04Determineconfirmationofreceipt
v 6 T05Printandsendconfirmationofreceipt
v 7 T10Determinenecessitytostopindication
v 8 T11CreatedocumentXrequestunlicensed
v 9 T12CheckdocumentXrequestunlicensed
v 10 T14DeterminedocumentXrequestunlicensed
v 11 T15PrintdocumentXrequestunlicensed
v 12 END
e 1 2  START__Confirmationofreceipt
e 2 3  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 5  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 4 7  T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
e 5 7  T04Determineconfirmationofreceipt__T10Determinenecessitytostopindication
e 6 7  T05Printandsendconfirmationofreceipt__T10Determinenecessitytostopindication
e 9 10  T12CheckdocumentXrequestunlicensed__T14DeterminedocumentXrequestunlicensed
e 10 11  T14DeterminedocumentXrequestunlicensed__T15PrintdocumentXrequestunlicensed
e 11 12  T15PrintdocumentXrequestunlicensed__END
e 7 8  T10Determinenecessitytostopindication__T11CreatedocumentXrequestunlicensed
e 8 9  T11CreatedocumentXrequestunlicensed__T12CheckdocumentXrequestunlicensed

XP
v 1 START
v 2 Confirmationofreceipt
v 3 T02Checkconfirmationofreceipt
v 4 T04Determineconfirmationofreceipt
v 5 T05Printandsendconfirmationofreceipt
v 6 T06Determinenecessityofstopadvice
v 7 T10Determinenecessitytostopindication
v 8 T11CreatedocumentXrequestunlicensed
v 9 T12CheckdocumentXrequestunlicensed
v 10 T14DeterminedocumentXrequestunlicensed
v 11 T15PrintdocumentXrequestunlicensed
v 12 END
e 1 2  START__Confirmationofreceipt
e 2 3  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 4  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 4 6  T04Determineconfirmationofreceipt__T06Determinenecessityofstopadvice
e 5 6  T05Printandsendconfirmationofreceipt__T06Determinenecessityofstopadvice
e 6 7  T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
e 9 10  T12CheckdocumentXrequestunlicensed__T14DeterminedocumentXrequestunlicensed
e 10 11  T14DeterminedocumentXrequestunlicensed__T15PrintdocumentXrequestunlicensed
e 11 12  T15PrintdocumentXrequestunlicensed__END
e 7 8  T10Determinenecessitytostopindication__T11CreatedocumentXrequestunlicensed
e 8 9  T11CreatedocumentXrequestunlicensed__T12CheckdocumentXrequestunlicensed

XP
v 1 START
v 2 Confirmationofreceipt
v 3 T02Checkconfirmationofreceipt
v 4 T06Determinenecessityofstopadvice
v 5 T10Determinenecessitytostopindication
v 6 T04Determineconfirmationofreceipt
v 7 T05Printandsendconfirmationofreceipt
v 8 T11CreatedocumentXrequestunlicensed
v 9 T12CheckdocumentXrequestunlicensed
v 10 T14DeterminedocumentXrequestunlicensed
v 11 T15PrintdocumentXrequestunlicensed
v 12 END
e 1 2  START__Confirmationofreceipt
e 2 3  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 6  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 4 5  T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
e 5 7  T10Determinenecessitytostopindication__T05Printandsendconfirmationofreceipt
e 5 9  T10Determinenecessitytostopindication__T12CheckdocumentXrequestunlicensed
e 9 10  T12CheckdocumentXrequestunlicensed__T14DeterminedocumentXrequestunlicensed
e 10 11  T14DeterminedocumentXrequestunlicensed__T15PrintdocumentXrequestunlicensed
e 11 12  T15PrintdocumentXrequestunlicensed__END
e 8 10  T11CreatedocumentXrequestunlicensed__T14DeterminedocumentXrequestunlicensed
e 7 8  T05Printandsendconfirmationofreceipt__T11CreatedocumentXrequestunlicensed

XP
v 1 START
v 2 Confirmationofreceipt
v 3 T02Checkconfirmationofreceipt
v 4 T04Determineconfirmationofreceipt
v 5 T05Printandsendconfirmationofreceipt
v 6 T06Determinenecessityofstopadvice
v 7 T10Determinenecessitytostopindication
v 8 T11CreatedocumentXrequestunlicensed
v 9 T12CheckdocumentXrequestunlicensed
v 10 T14DeterminedocumentXrequestunlicensed
v 11 T15PrintdocumentXrequestunlicensed
v 12 END
e 1 2  START__Confirmationofreceipt
e 2 3  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 4  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 4 6  T04Determineconfirmationofreceipt__T06Determinenecessityofstopadvice
e 5 6  T05Printandsendconfirmationofreceipt__T06Determinenecessityofstopadvice
e 6 7  T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
e 9 10  T12CheckdocumentXrequestunlicensed__T14DeterminedocumentXrequestunlicensed
e 10 11  T14DeterminedocumentXrequestunlicensed__T15PrintdocumentXrequestunlicensed
e 11 12  T15PrintdocumentXrequestunlicensed__END
e 7 8  T10Determinenecessitytostopindication__T11CreatedocumentXrequestunlicensed
e 8 9  T11CreatedocumentXrequestunlicensed__T12CheckdocumentXrequestunlicensed

XP
v 1 START
v 2 Confirmationofreceipt
v 3 T02Checkconfirmationofreceipt
v 4 T04Determineconfirmationofreceipt
v 5 T05Printandsendconfirmationofreceipt
v 6 T06Determinenecessityofstopadvice
v 7 T10Determinenecessitytostopindication
v 8 T16Reportreasonstoholdrequest
v 9 T17CheckreportYtostopindication
v 10 T18AdjustreportYtostopindicition
v 11 T17CheckreportYtostopindication
v 12 T18AdjustreportYtostopindicition
v 13 T17CheckreportYtostopindication
v 14 T18AdjustreportYtostopindicition
v 15 T17CheckreportYtostopindication
v 16 T18AdjustreportYtostopindicition
v 17 T17CheckreportYtostopindication
v 18 T19DeterminereportYtostopindication
v 19 T20PrintreportYtostopindication
v 20 END
e 1 2  START__Confirmationofreceipt
e 2 3  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 4  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 3 8  T02Checkconfirmationofreceipt__T16Reportreasonstoholdrequest
e 4 6  T04Determineconfirmationofreceipt__T06Determinenecessityofstopadvice
e 5 6  T05Printandsendconfirmationofreceipt__T06Determinenecessityofstopadvice
e 6 7  T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
e 7 20  T10Determinenecessitytostopindication__END
e 8 9  T16Reportreasonstoholdrequest__T17CheckreportYtostopindication
e 8 11  T16Reportreasonstoholdrequest__T17CheckreportYtostopindication
e 8 13  T16Reportreasonstoholdrequest__T17CheckreportYtostopindication
e 8 15  T16Reportreasonstoholdrequest__T17CheckreportYtostopindication
e 8 17  T16Reportreasonstoholdrequest__T17CheckreportYtostopindication
e 17 18  T17CheckreportYtostopindication__T19DeterminereportYtostopindication
e 18 19  T19DeterminereportYtostopindication__T20PrintreportYtostopindication
e 10 18  T18AdjustreportYtostopindicition__T19DeterminereportYtostopindication
e 9 10  T17CheckreportYtostopindication__T18AdjustreportYtostopindicition
e 12 18  T18AdjustreportYtostopindicition__T19DeterminereportYtostopindication
e 11 12  T17CheckreportYtostopindication__T18AdjustreportYtostopindicition
e 14 18  T18AdjustreportYtostopindicition__T19DeterminereportYtostopindication
e 13 14  T17CheckreportYtostopindication__T18AdjustreportYtostopindicition
e 16 18  T18AdjustreportYtostopindicition__T19DeterminereportYtostopindication
e 15 16  T17CheckreportYtostopindication__T18AdjustreportYtostopindicition

XP
v 1 START
v 2 Confirmationofreceipt
v 3 T02Checkconfirmationofreceipt
v 4 T04Determineconfirmationofreceipt
v 5 T05Printandsendconfirmationofreceipt
v 6 T06Determinenecessityofstopadvice
v 7 T10Determinenecessitytostopindication
v 8 T11CreatedocumentXrequestunlicensed
v 9 T12CheckdocumentXrequestunlicensed
v 10 T14DeterminedocumentXrequestunlicensed
v 11 T15PrintdocumentXrequestunlicensed
v 12 END
e 1 2  START__Confirmationofreceipt
e 2 3  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 4  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 4 6  T04Determineconfirmationofreceipt__T06Determinenecessityofstopadvice
e 5 6  T05Printandsendconfirmationofreceipt__T06Determinenecessityofstopadvice
e 6 7  T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
e 9 10  T12CheckdocumentXrequestunlicensed__T14DeterminedocumentXrequestunlicensed
e 10 11  T14DeterminedocumentXrequestunlicensed__T15PrintdocumentXrequestunlicensed
e 11 12  T15PrintdocumentXrequestunlicensed__END
e 7 8  T10Determinenecessitytostopindication__T11CreatedocumentXrequestunlicensed
e 8 9  T11CreatedocumentXrequestunlicensed__T12CheckdocumentXrequestunlicensed

XP
v 1 START
v 2 Confirmationofreceipt
v 3 T02Checkconfirmationofreceipt
v 4 T04Determineconfirmationofreceipt
v 5 T05Printandsendconfirmationofreceipt
v 6 T06Determinenecessityofstopadvice
v 7 T10Determinenecessitytostopindication
v 8 T11CreatedocumentXrequestunlicensed
v 9 T12CheckdocumentXrequestunlicensed
v 10 T14DeterminedocumentXrequestunlicensed
v 11 T15PrintdocumentXrequestunlicensed
v 12 END
e 1 2  START__Confirmationofreceipt
e 2 3  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 4  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 4 6  T04Determineconfirmationofreceipt__T06Determinenecessityofstopadvice
e 5 6  T05Printandsendconfirmationofreceipt__T06Determinenecessityofstopadvice
e 6 7  T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
e 9 10  T12CheckdocumentXrequestunlicensed__T14DeterminedocumentXrequestunlicensed
e 10 11  T14DeterminedocumentXrequestunlicensed__T15PrintdocumentXrequestunlicensed
e 11 12  T15PrintdocumentXrequestunlicensed__END
e 7 8  T10Determinenecessitytostopindication__T11CreatedocumentXrequestunlicensed
e 8 9  T11CreatedocumentXrequestunlicensed__T12CheckdocumentXrequestunlicensed

XP
v 1 START
v 2 Confirmationofreceipt
v 3 T02Checkconfirmationofreceipt
v 4 T04Determineconfirmationofreceipt
v 5 T05Printandsendconfirmationofreceipt
v 6 T06Determinenecessityofstopadvice
v 7 T10Determinenecessitytostopindication
v 8 T11CreatedocumentXrequestunlicensed
v 9 T12CheckdocumentXrequestunlicensed
v 10 T14DeterminedocumentXrequestunlicensed
v 11 T15PrintdocumentXrequestunlicensed
v 12 END
e 1 2  START__Confirmationofreceipt
e 2 3  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 4  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 4 6  T04Determineconfirmationofreceipt__T06Determinenecessityofstopadvice
e 5 6  T05Printandsendconfirmationofreceipt__T06Determinenecessityofstopadvice
e 6 7  T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
e 9 10  T12CheckdocumentXrequestunlicensed__T14DeterminedocumentXrequestunlicensed
e 10 11  T14DeterminedocumentXrequestunlicensed__T15PrintdocumentXrequestunlicensed
e 11 12  T15PrintdocumentXrequestunlicensed__END
e 7 8  T10Determinenecessitytostopindication__T11CreatedocumentXrequestunlicensed
e 8 9  T11CreatedocumentXrequestunlicensed__T12CheckdocumentXrequestunlicensed

XP
v 1 START
v 2 Confirmationofreceipt
v 3 T02Checkconfirmationofreceipt
v 4 T04Determineconfirmationofreceipt
v 5 T06Determinenecessityofstopadvice
v 6 T10Determinenecessitytostopindication
v 7 T05Printandsendconfirmationofreceipt
v 8 T11CreatedocumentXrequestunlicensed
v 9 END
e 1 2  START__Confirmationofreceipt
e 2 3  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 4  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 4 5  T04Determineconfirmationofreceipt__T06Determinenecessityofstopadvice
e 5 6  T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
e 6 7  T10Determinenecessitytostopindication__T05Printandsendconfirmationofreceipt
e 7 8  T05Printandsendconfirmationofreceipt__T11CreatedocumentXrequestunlicensed
e 8 9  T11CreatedocumentXrequestunlicensed__END

XP
v 1 START
v 2 Confirmationofreceipt
v 3 T02Checkconfirmationofreceipt
v 4 T04Determineconfirmationofreceipt
v 5 T05Printandsendconfirmationofreceipt
v 6 T06Determinenecessityofstopadvice
v 7 T10Determinenecessitytostopindication
v 8 T11CreatedocumentXrequestunlicensed
v 9 T12CheckdocumentXrequestunlicensed
v 10 T14DeterminedocumentXrequestunlicensed
v 11 T15PrintdocumentXrequestunlicensed
v 12 END
e 1 2  START__Confirmationofreceipt
e 2 3  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 4  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 4 6  T04Determineconfirmationofreceipt__T06Determinenecessityofstopadvice
e 5 6  T05Printandsendconfirmationofreceipt__T06Determinenecessityofstopadvice
e 6 7  T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
e 9 10  T12CheckdocumentXrequestunlicensed__T14DeterminedocumentXrequestunlicensed
e 10 11  T14DeterminedocumentXrequestunlicensed__T15PrintdocumentXrequestunlicensed
e 11 12  T15PrintdocumentXrequestunlicensed__END
e 7 8  T10Determinenecessitytostopindication__T11CreatedocumentXrequestunlicensed
e 8 9  T11CreatedocumentXrequestunlicensed__T12CheckdocumentXrequestunlicensed

XP
v 1 START
v 2 Confirmationofreceipt
v 3 T02Checkconfirmationofreceipt
v 4 T04Determineconfirmationofreceipt
v 5 T05Printandsendconfirmationofreceipt
v 6 T06Determinenecessityofstopadvice
v 7 T10Determinenecessitytostopindication
v 8 T11CreatedocumentXrequestunlicensed
v 9 T12CheckdocumentXrequestunlicensed
v 10 T14DeterminedocumentXrequestunlicensed
v 11 T15PrintdocumentXrequestunlicensed
v 12 END
e 1 2  START__Confirmationofreceipt
e 2 3  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 4  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 4 6  T04Determineconfirmationofreceipt__T06Determinenecessityofstopadvice
e 5 6  T05Printandsendconfirmationofreceipt__T06Determinenecessityofstopadvice
e 6 7  T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
e 9 10  T12CheckdocumentXrequestunlicensed__T14DeterminedocumentXrequestunlicensed
e 10 11  T14DeterminedocumentXrequestunlicensed__T15PrintdocumentXrequestunlicensed
e 11 12  T15PrintdocumentXrequestunlicensed__END
e 7 8  T10Determinenecessitytostopindication__T11CreatedocumentXrequestunlicensed
e 8 9  T11CreatedocumentXrequestunlicensed__T12CheckdocumentXrequestunlicensed

XP
v 1 START
v 2 Confirmationofreceipt
v 3 T02Checkconfirmationofreceipt
v 4 T04Determineconfirmationofreceipt
v 5 T05Printandsendconfirmationofreceipt
v 6 T06Determinenecessityofstopadvice
v 7 T10Determinenecessitytostopindication
v 8 T11CreatedocumentXrequestunlicensed
v 9 T12CheckdocumentXrequestunlicensed
v 10 T14DeterminedocumentXrequestunlicensed
v 11 T15PrintdocumentXrequestunlicensed
v 12 END
e 1 2  START__Confirmationofreceipt
e 2 3  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 4  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 4 6  T04Determineconfirmationofreceipt__T06Determinenecessityofstopadvice
e 5 6  T05Printandsendconfirmationofreceipt__T06Determinenecessityofstopadvice
e 6 7  T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
e 9 10  T12CheckdocumentXrequestunlicensed__T14DeterminedocumentXrequestunlicensed
e 10 11  T14DeterminedocumentXrequestunlicensed__T15PrintdocumentXrequestunlicensed
e 11 12  T15PrintdocumentXrequestunlicensed__END
e 7 8  T10Determinenecessitytostopindication__T11CreatedocumentXrequestunlicensed
e 8 9  T11CreatedocumentXrequestunlicensed__T12CheckdocumentXrequestunlicensed

XP
v 1 START
v 2 Confirmationofreceipt
v 3 T02Checkconfirmationofreceipt
v 4 T04Determineconfirmationofreceipt
v 5 T05Printandsendconfirmationofreceipt
v 6 T06Determinenecessityofstopadvice
v 7 T10Determinenecessitytostopindication
v 8 T11CreatedocumentXrequestunlicensed
v 9 T12CheckdocumentXrequestunlicensed
v 10 T14DeterminedocumentXrequestunlicensed
v 11 T15PrintdocumentXrequestunlicensed
v 12 END
e 1 2  START__Confirmationofreceipt
e 2 3  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 4  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 4 6  T04Determineconfirmationofreceipt__T06Determinenecessityofstopadvice
e 5 6  T05Printandsendconfirmationofreceipt__T06Determinenecessityofstopadvice
e 6 7  T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
e 9 10  T12CheckdocumentXrequestunlicensed__T14DeterminedocumentXrequestunlicensed
e 10 11  T14DeterminedocumentXrequestunlicensed__T15PrintdocumentXrequestunlicensed
e 11 12  T15PrintdocumentXrequestunlicensed__END
e 7 8  T10Determinenecessitytostopindication__T11CreatedocumentXrequestunlicensed
e 8 9  T11CreatedocumentXrequestunlicensed__T12CheckdocumentXrequestunlicensed

XP
v 1 START
v 2 Confirmationofreceipt
v 3 T06Determinenecessityofstopadvice
v 4 T02Checkconfirmationofreceipt
v 5 T04Determineconfirmationofreceipt
v 6 T05Printandsendconfirmationofreceipt
v 7 T10Determinenecessitytostopindication
v 8 T11CreatedocumentXrequestunlicensed
v 9 T12CheckdocumentXrequestunlicensed
v 10 T14DeterminedocumentXrequestunlicensed
v 11 T15PrintdocumentXrequestunlicensed
v 12 END
e 1 2  START__Confirmationofreceipt
e 2 4  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 4  T06Determinenecessityofstopadvice__T02Checkconfirmationofreceipt
e 4 5  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 5 7  T04Determineconfirmationofreceipt__T10Determinenecessitytostopindication
e 6 7  T05Printandsendconfirmationofreceipt__T10Determinenecessitytostopindication
e 9 10  T12CheckdocumentXrequestunlicensed__T14DeterminedocumentXrequestunlicensed
e 10 11  T14DeterminedocumentXrequestunlicensed__T15PrintdocumentXrequestunlicensed
e 11 12  T15PrintdocumentXrequestunlicensed__END
e 7 8  T10Determinenecessitytostopindication__T11CreatedocumentXrequestunlicensed
e 8 9  T11CreatedocumentXrequestunlicensed__T12CheckdocumentXrequestunlicensed

XP
v 1 START
v 2 Confirmationofreceipt
v 3 T02Checkconfirmationofreceipt
v 4 T04Determineconfirmationofreceipt
v 5 T05Printandsendconfirmationofreceipt
v 6 T06Determinenecessityofstopadvice
v 7 T10Determinenecessitytostopindication
v 8 T11CreatedocumentXrequestunlicensed
v 9 T12CheckdocumentXrequestunlicensed
v 10 T14DeterminedocumentXrequestunlicensed
v 11 T15PrintdocumentXrequestunlicensed
v 12 END
e 1 2  START__Confirmationofreceipt
e 2 3  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 4  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 4 6  T04Determineconfirmationofreceipt__T06Determinenecessityofstopadvice
e 5 6  T05Printandsendconfirmationofreceipt__T06Determinenecessityofstopadvice
e 6 7  T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
e 9 10  T12CheckdocumentXrequestunlicensed__T14DeterminedocumentXrequestunlicensed
e 10 11  T14DeterminedocumentXrequestunlicensed__T15PrintdocumentXrequestunlicensed
e 11 12  T15PrintdocumentXrequestunlicensed__END
e 7 8  T10Determinenecessitytostopindication__T11CreatedocumentXrequestunlicensed
e 8 9  T11CreatedocumentXrequestunlicensed__T12CheckdocumentXrequestunlicensed

XP
v 1 START
v 2 Confirmationofreceipt
v 3 T02Checkconfirmationofreceipt
v 4 T04Determineconfirmationofreceipt
v 5 T05Printandsendconfirmationofreceipt
v 6 T06Determinenecessityofstopadvice
v 7 T10Determinenecessitytostopindication
v 8 T11CreatedocumentXrequestunlicensed
v 9 T12CheckdocumentXrequestunlicensed
v 10 T14DeterminedocumentXrequestunlicensed
v 11 T15PrintdocumentXrequestunlicensed
v 12 END
e 1 2  START__Confirmationofreceipt
e 2 3  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 4  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 4 6  T04Determineconfirmationofreceipt__T06Determinenecessityofstopadvice
e 5 6  T05Printandsendconfirmationofreceipt__T06Determinenecessityofstopadvice
e 6 7  T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
e 9 10  T12CheckdocumentXrequestunlicensed__T14DeterminedocumentXrequestunlicensed
e 10 11  T14DeterminedocumentXrequestunlicensed__T15PrintdocumentXrequestunlicensed
e 11 12  T15PrintdocumentXrequestunlicensed__END
e 7 8  T10Determinenecessitytostopindication__T11CreatedocumentXrequestunlicensed
e 8 9  T11CreatedocumentXrequestunlicensed__T12CheckdocumentXrequestunlicensed

XP
v 1 START
v 2 Confirmationofreceipt
v 3 T06Determinenecessityofstopadvice
v 4 T10Determinenecessitytostopindication
v 5 T02Checkconfirmationofreceipt
v 6 T04Determineconfirmationofreceipt
v 7 T05Printandsendconfirmationofreceipt
v 8 T11CreatedocumentXrequestunlicensed
v 9 T12CheckdocumentXrequestunlicensed
v 10 T14DeterminedocumentXrequestunlicensed
v 11 T15PrintdocumentXrequestunlicensed
v 12 END
e 1 2  START__Confirmationofreceipt
e 2 5  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 4  T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
e 4 5  T10Determinenecessitytostopindication__T02Checkconfirmationofreceipt
e 4 7  T10Determinenecessitytostopindication__T05Printandsendconfirmationofreceipt
e 4 9  T10Determinenecessitytostopindication__T12CheckdocumentXrequestunlicensed
e 5 6  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 9 10  T12CheckdocumentXrequestunlicensed__T14DeterminedocumentXrequestunlicensed
e 10 11  T14DeterminedocumentXrequestunlicensed__T15PrintdocumentXrequestunlicensed
e 11 12  T15PrintdocumentXrequestunlicensed__END
e 8 10  T11CreatedocumentXrequestunlicensed__T14DeterminedocumentXrequestunlicensed
e 7 8  T05Printandsendconfirmationofreceipt__T11CreatedocumentXrequestunlicensed

XP
v 1 START
v 2 Confirmationofreceipt
v 3 T02Checkconfirmationofreceipt
v 4 T04Determineconfirmationofreceipt
v 5 T05Printandsendconfirmationofreceipt
v 6 T06Determinenecessityofstopadvice
v 7 T10Determinenecessitytostopindication
v 8 T11CreatedocumentXrequestunlicensed
v 9 T12CheckdocumentXrequestunlicensed
v 10 T14DeterminedocumentXrequestunlicensed
v 11 T15PrintdocumentXrequestunlicensed
v 12 END
e 1 2  START__Confirmationofreceipt
e 2 3  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 4  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 4 6  T04Determineconfirmationofreceipt__T06Determinenecessityofstopadvice
e 5 6  T05Printandsendconfirmationofreceipt__T06Determinenecessityofstopadvice
e 6 7  T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
e 9 10  T12CheckdocumentXrequestunlicensed__T14DeterminedocumentXrequestunlicensed
e 10 11  T14DeterminedocumentXrequestunlicensed__T15PrintdocumentXrequestunlicensed
e 11 12  T15PrintdocumentXrequestunlicensed__END
e 7 8  T10Determinenecessitytostopindication__T11CreatedocumentXrequestunlicensed
e 8 9  T11CreatedocumentXrequestunlicensed__T12CheckdocumentXrequestunlicensed

XP
v 1 START
v 2 Confirmationofreceipt
v 3 T02Checkconfirmationofreceipt
v 4 T04Determineconfirmationofreceipt
v 5 T05Printandsendconfirmationofreceipt
v 6 T06Determinenecessityofstopadvice
v 7 T10Determinenecessitytostopindication
v 8 T11CreatedocumentXrequestunlicensed
v 9 T12CheckdocumentXrequestunlicensed
v 10 T14DeterminedocumentXrequestunlicensed
v 11 T15PrintdocumentXrequestunlicensed
v 12 END
e 1 2  START__Confirmationofreceipt
e 2 3  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 4  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 4 6  T04Determineconfirmationofreceipt__T06Determinenecessityofstopadvice
e 5 6  T05Printandsendconfirmationofreceipt__T06Determinenecessityofstopadvice
e 6 7  T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
e 9 10  T12CheckdocumentXrequestunlicensed__T14DeterminedocumentXrequestunlicensed
e 10 11  T14DeterminedocumentXrequestunlicensed__T15PrintdocumentXrequestunlicensed
e 11 12  T15PrintdocumentXrequestunlicensed__END
e 7 8  T10Determinenecessitytostopindication__T11CreatedocumentXrequestunlicensed
e 8 9  T11CreatedocumentXrequestunlicensed__T12CheckdocumentXrequestunlicensed

XP
v 1 START
v 2 Confirmationofreceipt
v 3 T02Checkconfirmationofreceipt
v 4 T04Determineconfirmationofreceipt
v 5 T05Printandsendconfirmationofreceipt
v 6 T06Determinenecessityofstopadvice
v 7 T10Determinenecessitytostopindication
v 8 T16Reportreasonstoholdrequest
v 9 T17CheckreportYtostopindication
v 10 T18AdjustreportYtostopindicition
v 11 T17CheckreportYtostopindication
v 12 T18AdjustreportYtostopindicition
v 13 T17CheckreportYtostopindication
v 14 T19DeterminereportYtostopindication
v 15 T20PrintreportYtostopindication
v 16 END
e 1 2  START__Confirmationofreceipt
e 2 3  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 4  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 3 8  T02Checkconfirmationofreceipt__T16Reportreasonstoholdrequest
e 4 6  T04Determineconfirmationofreceipt__T06Determinenecessityofstopadvice
e 5 6  T05Printandsendconfirmationofreceipt__T06Determinenecessityofstopadvice
e 6 7  T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
e 7 16  T10Determinenecessitytostopindication__END
e 8 9  T16Reportreasonstoholdrequest__T17CheckreportYtostopindication
e 8 11  T16Reportreasonstoholdrequest__T17CheckreportYtostopindication
e 8 13  T16Reportreasonstoholdrequest__T17CheckreportYtostopindication
e 13 14  T17CheckreportYtostopindication__T19DeterminereportYtostopindication
e 14 15  T19DeterminereportYtostopindication__T20PrintreportYtostopindication
e 10 14  T18AdjustreportYtostopindicition__T19DeterminereportYtostopindication
e 9 10  T17CheckreportYtostopindication__T18AdjustreportYtostopindicition
e 12 14  T18AdjustreportYtostopindicition__T19DeterminereportYtostopindication
e 11 12  T17CheckreportYtostopindication__T18AdjustreportYtostopindicition

XP
v 1 START
v 2 Confirmationofreceipt
v 3 T02Checkconfirmationofreceipt
v 4 T04Determineconfirmationofreceipt
v 5 T05Printandsendconfirmationofreceipt
v 6 T06Determinenecessityofstopadvice
v 7 T10Determinenecessitytostopindication
v 8 T11CreatedocumentXrequestunlicensed
v 9 T12CheckdocumentXrequestunlicensed
v 10 T14DeterminedocumentXrequestunlicensed
v 11 T15PrintdocumentXrequestunlicensed
v 12 END
e 1 2  START__Confirmationofreceipt
e 2 3  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 4  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 4 6  T04Determineconfirmationofreceipt__T06Determinenecessityofstopadvice
e 5 6  T05Printandsendconfirmationofreceipt__T06Determinenecessityofstopadvice
e 6 7  T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
e 9 10  T12CheckdocumentXrequestunlicensed__T14DeterminedocumentXrequestunlicensed
e 10 11  T14DeterminedocumentXrequestunlicensed__T15PrintdocumentXrequestunlicensed
e 11 12  T15PrintdocumentXrequestunlicensed__END
e 7 8  T10Determinenecessitytostopindication__T11CreatedocumentXrequestunlicensed
e 8 9  T11CreatedocumentXrequestunlicensed__T12CheckdocumentXrequestunlicensed

XP
v 1 START
v 2 Confirmationofreceipt
v 3 T02Checkconfirmationofreceipt
v 4 T04Determineconfirmationofreceipt
v 5 T05Printandsendconfirmationofreceipt
v 6 T06Determinenecessityofstopadvice
v 7 T10Determinenecessitytostopindication
v 8 T11CreatedocumentXrequestunlicensed
v 9 T12CheckdocumentXrequestunlicensed
v 10 T14DeterminedocumentXrequestunlicensed
v 11 T15PrintdocumentXrequestunlicensed
v 12 END
e 1 2  START__Confirmationofreceipt
e 2 3  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 4  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 4 6  T04Determineconfirmationofreceipt__T06Determinenecessityofstopadvice
e 5 6  T05Printandsendconfirmationofreceipt__T06Determinenecessityofstopadvice
e 6 7  T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
e 9 10  T12CheckdocumentXrequestunlicensed__T14DeterminedocumentXrequestunlicensed
e 10 11  T14DeterminedocumentXrequestunlicensed__T15PrintdocumentXrequestunlicensed
e 11 12  T15PrintdocumentXrequestunlicensed__END
e 7 8  T10Determinenecessitytostopindication__T11CreatedocumentXrequestunlicensed
e 8 9  T11CreatedocumentXrequestunlicensed__T12CheckdocumentXrequestunlicensed

XP
v 1 START
v 2 Confirmationofreceipt
v 3 T02Checkconfirmationofreceipt
v 4 T04Determineconfirmationofreceipt
v 5 T05Printandsendconfirmationofreceipt
v 6 T06Determinenecessityofstopadvice
v 7 T08Draftandsendrequestforadvice
v 8 T09-3Processorreceiveexternaladvicefromparty3
v 9 T09-1Processorreceiveexternaladvicefromparty1
v 10 T07-3Draftinternadviceholdforaspect3
v 11 T07-5Draftinternadviceaspect5
v 12 T09-2Processorreceiveexternaladvicefromparty2
v 13 T09-4Processorreceiveexternaladvicefromparty4
v 14 T07-2Draftinternadviceaspect2
v 15 T07-1Draftinternadviceaspect1
v 16 T07-4Draftinternaladvicetoholdfortype4
v 17 T06Determinenecessityofstopadvice
v 18 T06Determinenecessityofstopadvice
v 19 T06Determinenecessityofstopadvice
v 20 END
e 1 2  START__Confirmationofreceipt
e 2 3  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 4  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 4 6  T04Determineconfirmationofreceipt__T06Determinenecessityofstopadvice
e 5 6  T05Printandsendconfirmationofreceipt__T06Determinenecessityofstopadvice
e 6 7  T06Determinenecessityofstopadvice__T08Draftandsendrequestforadvice
e 7 8  T08Draftandsendrequestforadvice__T09-3Processorreceiveexternaladvicefromparty3
e 7 15  T08Draftandsendrequestforadvice__T07-1Draftinternadviceaspect1
e 13 14  T09-4Processorreceiveexternaladvicefromparty4__T07-2Draftinternadviceaspect2
e 17 18  T06Determinenecessityofstopadvice__T06Determinenecessityofstopadvice
e 18 19  T06Determinenecessityofstopadvice__T06Determinenecessityofstopadvice
e 19 20  T06Determinenecessityofstopadvice__END
e 8 10  T09-3Processorreceiveexternaladvicefromparty3__T07-3Draftinternadviceholdforaspect3
e 9 10  T09-1Processorreceiveexternaladvicefromparty1__T07-3Draftinternadviceholdforaspect3
e 10 11  T07-3Draftinternadviceholdforaspect3__T07-5Draftinternadviceaspect5
e 11 12  T07-5Draftinternadviceaspect5__T09-2Processorreceiveexternaladvicefromparty2
e 12 13  T09-2Processorreceiveexternaladvicefromparty2__T09-4Processorreceiveexternaladvicefromparty4
e 14 16  T07-2Draftinternadviceaspect2__T07-4Draftinternaladvicetoholdfortype4
e 15 16  T07-1Draftinternadviceaspect1__T07-4Draftinternaladvicetoholdfortype4
e 16 17  T07-4Draftinternaladvicetoholdfortype4__T06Determinenecessityofstopadvice

XP
v 1 START
v 2 Confirmationofreceipt
v 3 T02Checkconfirmationofreceipt
v 4 T03Adjustconfirmationofreceipt
v 5 T02Checkconfirmationofreceipt
v 6 T03Adjustconfirmationofreceipt
v 7 T02Checkconfirmationofreceipt
v 8 T04Determineconfirmationofreceipt
v 9 T05Printandsendconfirmationofreceipt
v 10 T06Determinenecessityofstopadvice
v 11 T07-1Draftinternadviceaspect1
v 12 T06Determinenecessityofstopadvice
v 13 T07-1Draftinternadviceaspect1
v 14 T06Determinenecessityofstopadvice
v 15 T10Determinenecessitytostopindication
v 16 T11CreatedocumentXrequestunlicensed
v 17 T12CheckdocumentXrequestunlicensed
v 18 T14DeterminedocumentXrequestunlicensed
v 19 T15PrintdocumentXrequestunlicensed
v 20 END
e 1 2  START__Confirmationofreceipt
e 2 3  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 8  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 4 5  T03Adjustconfirmationofreceipt__T02Checkconfirmationofreceipt
e 5 8  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 6 7  T03Adjustconfirmationofreceipt__T02Checkconfirmationofreceipt
e 7 8  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 8 10  T04Determineconfirmationofreceipt__T06Determinenecessityofstopadvice
e 9 10  T05Printandsendconfirmationofreceipt__T06Determinenecessityofstopadvice
e 10 11  T06Determinenecessityofstopadvice__T07-1Draftinternadviceaspect1
e 11 12  T07-1Draftinternadviceaspect1__T06Determinenecessityofstopadvice
e 12 13  T06Determinenecessityofstopadvice__T07-1Draftinternadviceaspect1
e 13 14  T07-1Draftinternadviceaspect1__T06Determinenecessityofstopadvice
e 14 15  T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
e 17 18  T12CheckdocumentXrequestunlicensed__T14DeterminedocumentXrequestunlicensed
e 18 19  T14DeterminedocumentXrequestunlicensed__T15PrintdocumentXrequestunlicensed
e 19 20  T15PrintdocumentXrequestunlicensed__END
e 15 16  T10Determinenecessitytostopindication__T11CreatedocumentXrequestunlicensed
e 16 17  T11CreatedocumentXrequestunlicensed__T12CheckdocumentXrequestunlicensed

XP
v 1 START
v 2 Confirmationofreceipt
v 3 T02Checkconfirmationofreceipt
v 4 T04Determineconfirmationofreceipt
v 5 T05Printandsendconfirmationofreceipt
v 6 T06Determinenecessityofstopadvice
v 7 T10Determinenecessitytostopindication
v 8 T11CreatedocumentXrequestunlicensed
v 9 T12CheckdocumentXrequestunlicensed
v 10 T14DeterminedocumentXrequestunlicensed
v 11 T15PrintdocumentXrequestunlicensed
v 12 END
e 1 2  START__Confirmationofreceipt
e 2 3  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 4  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 4 6  T04Determineconfirmationofreceipt__T06Determinenecessityofstopadvice
e 5 6  T05Printandsendconfirmationofreceipt__T06Determinenecessityofstopadvice
e 6 7  T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
e 9 10  T12CheckdocumentXrequestunlicensed__T14DeterminedocumentXrequestunlicensed
e 10 11  T14DeterminedocumentXrequestunlicensed__T15PrintdocumentXrequestunlicensed
e 11 12  T15PrintdocumentXrequestunlicensed__END
e 7 8  T10Determinenecessitytostopindication__T11CreatedocumentXrequestunlicensed
e 8 9  T11CreatedocumentXrequestunlicensed__T12CheckdocumentXrequestunlicensed

XP
v 1 START
v 2 Confirmationofreceipt
v 3 T02Checkconfirmationofreceipt
v 4 T04Determineconfirmationofreceipt
v 5 T05Printandsendconfirmationofreceipt
v 6 T06Determinenecessityofstopadvice
v 7 T07-3Draftinternadviceholdforaspect3
v 8 T07-2Draftinternadviceaspect2
v 9 T06Determinenecessityofstopadvice
v 10 T07-2Draftinternadviceaspect2
v 11 T07-3Draftinternadviceholdforaspect3
v 12 T06Determinenecessityofstopadvice
v 13 T10Determinenecessitytostopindication
v 14 END
e 1 2  START__Confirmationofreceipt
e 2 3  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 4  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 4 6  T04Determineconfirmationofreceipt__T06Determinenecessityofstopadvice
e 5 6  T05Printandsendconfirmationofreceipt__T06Determinenecessityofstopadvice
e 8 9  T07-2Draftinternadviceaspect2__T06Determinenecessityofstopadvice
e 12 13  T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
e 13 14  T10Determinenecessitytostopindication__END
e 7 9  T07-3Draftinternadviceholdforaspect3__T06Determinenecessityofstopadvice
e 9 11  T06Determinenecessityofstopadvice__T07-3Draftinternadviceholdforaspect3
e 10 11  T07-2Draftinternadviceaspect2__T07-3Draftinternadviceholdforaspect3
e 11 12  T07-3Draftinternadviceholdforaspect3__T06Determinenecessityofstopadvice

XP
v 1 START
v 2 Confirmationofreceipt
v 3 T02Checkconfirmationofreceipt
v 4 T06Determinenecessityofstopadvice
v 5 T10Determinenecessitytostopindication
v 6 T11CreatedocumentXrequestunlicensed
v 7 T04Determineconfirmationofreceipt
v 8 T05Printandsendconfirmationofreceipt
v 9 T12CheckdocumentXrequestunlicensed
v 10 T14DeterminedocumentXrequestunlicensed
v 11 T15PrintdocumentXrequestunlicensed
v 12 END
e 1 2  START__Confirmationofreceipt
e 2 3  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 4 5  T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
e 8 10  T05Printandsendconfirmationofreceipt__T14DeterminedocumentXrequestunlicensed
e 9 10  T12CheckdocumentXrequestunlicensed__T14DeterminedocumentXrequestunlicensed
e 10 11  T14DeterminedocumentXrequestunlicensed__T15PrintdocumentXrequestunlicensed
e 11 12  T15PrintdocumentXrequestunlicensed__END
e 3 6  T02Checkconfirmationofreceipt__T11CreatedocumentXrequestunlicensed
e 6 8  T11CreatedocumentXrequestunlicensed__T05Printandsendconfirmationofreceipt
e 6 9  T11CreatedocumentXrequestunlicensed__T12CheckdocumentXrequestunlicensed

XP
v 1 START
v 2 Confirmationofreceipt
v 3 T02Checkconfirmationofreceipt
v 4 T06Determinenecessityofstopadvice
v 5 T10Determinenecessitytostopindication
v 6 T04Determineconfirmationofreceipt
v 7 T05Printandsendconfirmationofreceipt
v 8 T11CreatedocumentXrequestunlicensed
v 9 T12CheckdocumentXrequestunlicensed
v 10 T14DeterminedocumentXrequestunlicensed
v 11 T15PrintdocumentXrequestunlicensed
v 12 END
e 1 2  START__Confirmationofreceipt
e 2 3  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 6  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 4 5  T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
e 5 7  T10Determinenecessitytostopindication__T05Printandsendconfirmationofreceipt
e 5 9  T10Determinenecessitytostopindication__T12CheckdocumentXrequestunlicensed
e 9 10  T12CheckdocumentXrequestunlicensed__T14DeterminedocumentXrequestunlicensed
e 10 11  T14DeterminedocumentXrequestunlicensed__T15PrintdocumentXrequestunlicensed
e 11 12  T15PrintdocumentXrequestunlicensed__END
e 8 10  T11CreatedocumentXrequestunlicensed__T14DeterminedocumentXrequestunlicensed
e 7 8  T05Printandsendconfirmationofreceipt__T11CreatedocumentXrequestunlicensed

XP
v 1 START
v 2 Confirmationofreceipt
v 3 T02Checkconfirmationofreceipt
v 4 T06Determinenecessityofstopadvice
v 5 T10Determinenecessitytostopindication
v 6 T04Determineconfirmationofreceipt
v 7 T05Printandsendconfirmationofreceipt
v 8 T11CreatedocumentXrequestunlicensed
v 9 T12CheckdocumentXrequestunlicensed
v 10 T14DeterminedocumentXrequestunlicensed
v 11 T15PrintdocumentXrequestunlicensed
v 12 END
e 1 2  START__Confirmationofreceipt
e 2 3  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 6  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 4 5  T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
e 5 7  T10Determinenecessitytostopindication__T05Printandsendconfirmationofreceipt
e 5 9  T10Determinenecessitytostopindication__T12CheckdocumentXrequestunlicensed
e 9 10  T12CheckdocumentXrequestunlicensed__T14DeterminedocumentXrequestunlicensed
e 10 11  T14DeterminedocumentXrequestunlicensed__T15PrintdocumentXrequestunlicensed
e 11 12  T15PrintdocumentXrequestunlicensed__END
e 8 10  T11CreatedocumentXrequestunlicensed__T14DeterminedocumentXrequestunlicensed
e 7 8  T05Printandsendconfirmationofreceipt__T11CreatedocumentXrequestunlicensed

XP
v 1 START
v 2 Confirmationofreceipt
v 3 T02Checkconfirmationofreceipt
v 4 T04Determineconfirmationofreceipt
v 5 T05Printandsendconfirmationofreceipt
v 6 T06Determinenecessityofstopadvice
v 7 T10Determinenecessitytostopindication
v 8 T11CreatedocumentXrequestunlicensed
v 9 T12CheckdocumentXrequestunlicensed
v 10 T14DeterminedocumentXrequestunlicensed
v 11 T15PrintdocumentXrequestunlicensed
v 12 END
e 1 2  START__Confirmationofreceipt
e 2 3  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 4  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 4 6  T04Determineconfirmationofreceipt__T06Determinenecessityofstopadvice
e 5 6  T05Printandsendconfirmationofreceipt__T06Determinenecessityofstopadvice
e 6 7  T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
e 9 10  T12CheckdocumentXrequestunlicensed__T14DeterminedocumentXrequestunlicensed
e 10 11  T14DeterminedocumentXrequestunlicensed__T15PrintdocumentXrequestunlicensed
e 11 12  T15PrintdocumentXrequestunlicensed__END
e 7 8  T10Determinenecessitytostopindication__T11CreatedocumentXrequestunlicensed
e 8 9  T11CreatedocumentXrequestunlicensed__T12CheckdocumentXrequestunlicensed

XP
v 1 START
v 2 Confirmationofreceipt
v 3 T02Checkconfirmationofreceipt
v 4 T04Determineconfirmationofreceipt
v 5 T05Printandsendconfirmationofreceipt
v 6 T06Determinenecessityofstopadvice
v 7 T10Determinenecessitytostopindication
v 8 T11CreatedocumentXrequestunlicensed
v 9 T12CheckdocumentXrequestunlicensed
v 10 T14DeterminedocumentXrequestunlicensed
v 11 T15PrintdocumentXrequestunlicensed
v 12 END
e 1 2  START__Confirmationofreceipt
e 2 3  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 4  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 4 6  T04Determineconfirmationofreceipt__T06Determinenecessityofstopadvice
e 5 6  T05Printandsendconfirmationofreceipt__T06Determinenecessityofstopadvice
e 6 7  T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
e 9 10  T12CheckdocumentXrequestunlicensed__T14DeterminedocumentXrequestunlicensed
e 10 11  T14DeterminedocumentXrequestunlicensed__T15PrintdocumentXrequestunlicensed
e 11 12  T15PrintdocumentXrequestunlicensed__END
e 7 8  T10Determinenecessitytostopindication__T11CreatedocumentXrequestunlicensed
e 8 9  T11CreatedocumentXrequestunlicensed__T12CheckdocumentXrequestunlicensed

XP
v 1 START
v 2 Confirmationofreceipt
v 3 T06Determinenecessityofstopadvice
v 4 T02Checkconfirmationofreceipt
v 5 T04Determineconfirmationofreceipt
v 6 T10Determinenecessitytostopindication
v 7 T05Printandsendconfirmationofreceipt
v 8 T11CreatedocumentXrequestunlicensed
v 9 T12CheckdocumentXrequestunlicensed
v 10 T14DeterminedocumentXrequestunlicensed
v 11 T15PrintdocumentXrequestunlicensed
v 12 END
e 1 2  START__Confirmationofreceipt
e 2 4  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 4  T06Determinenecessityofstopadvice__T02Checkconfirmationofreceipt
e 4 5  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 5 6  T04Determineconfirmationofreceipt__T10Determinenecessitytostopindication
e 6 7  T10Determinenecessitytostopindication__T05Printandsendconfirmationofreceipt
e 6 9  T10Determinenecessitytostopindication__T12CheckdocumentXrequestunlicensed
e 9 10  T12CheckdocumentXrequestunlicensed__T14DeterminedocumentXrequestunlicensed
e 10 11  T14DeterminedocumentXrequestunlicensed__T15PrintdocumentXrequestunlicensed
e 11 12  T15PrintdocumentXrequestunlicensed__END
e 8 10  T11CreatedocumentXrequestunlicensed__T14DeterminedocumentXrequestunlicensed
e 7 8  T05Printandsendconfirmationofreceipt__T11CreatedocumentXrequestunlicensed

XP
v 1 START
v 2 Confirmationofreceipt
v 3 T02Checkconfirmationofreceipt
v 4 T04Determineconfirmationofreceipt
v 5 T05Printandsendconfirmationofreceipt
v 6 T06Determinenecessityofstopadvice
v 7 T10Determinenecessitytostopindication
v 8 T11CreatedocumentXrequestunlicensed
v 9 T12CheckdocumentXrequestunlicensed
v 10 T14DeterminedocumentXrequestunlicensed
v 11 T15PrintdocumentXrequestunlicensed
v 12 END
e 1 2  START__Confirmationofreceipt
e 2 3  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 4  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 4 6  T04Determineconfirmationofreceipt__T06Determinenecessityofstopadvice
e 5 6  T05Printandsendconfirmationofreceipt__T06Determinenecessityofstopadvice
e 6 7  T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
e 9 10  T12CheckdocumentXrequestunlicensed__T14DeterminedocumentXrequestunlicensed
e 10 11  T14DeterminedocumentXrequestunlicensed__T15PrintdocumentXrequestunlicensed
e 11 12  T15PrintdocumentXrequestunlicensed__END
e 7 8  T10Determinenecessitytostopindication__T11CreatedocumentXrequestunlicensed
e 8 9  T11CreatedocumentXrequestunlicensed__T12CheckdocumentXrequestunlicensed

XP
v 1 START
v 2 Confirmationofreceipt
v 3 T02Checkconfirmationofreceipt
v 4 T04Determineconfirmationofreceipt
v 5 T05Printandsendconfirmationofreceipt
v 6 T06Determinenecessityofstopadvice
v 7 T10Determinenecessitytostopindication
v 8 T11CreatedocumentXrequestunlicensed
v 9 T12CheckdocumentXrequestunlicensed
v 10 T14DeterminedocumentXrequestunlicensed
v 11 T15PrintdocumentXrequestunlicensed
v 12 END
e 1 2  START__Confirmationofreceipt
e 2 3  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 4  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 4 6  T04Determineconfirmationofreceipt__T06Determinenecessityofstopadvice
e 5 6  T05Printandsendconfirmationofreceipt__T06Determinenecessityofstopadvice
e 6 7  T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
e 9 10  T12CheckdocumentXrequestunlicensed__T14DeterminedocumentXrequestunlicensed
e 10 11  T14DeterminedocumentXrequestunlicensed__T15PrintdocumentXrequestunlicensed
e 11 12  T15PrintdocumentXrequestunlicensed__END
e 7 8  T10Determinenecessitytostopindication__T11CreatedocumentXrequestunlicensed
e 8 9  T11CreatedocumentXrequestunlicensed__T12CheckdocumentXrequestunlicensed

XP
v 1 START
v 2 Confirmationofreceipt
v 3 T06Determinenecessityofstopadvice
v 4 T07-4Draftinternaladvicetoholdfortype4
v 5 T06Determinenecessityofstopadvice
v 6 T10Determinenecessitytostopindication
v 7 T02Checkconfirmationofreceipt
v 8 T04Determineconfirmationofreceipt
v 9 T05Printandsendconfirmationofreceipt
v 10 END
e 1 2  START__Confirmationofreceipt
e 2 7  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 5 6  T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
e 6 7  T10Determinenecessitytostopindication__T02Checkconfirmationofreceipt
e 6 9  T10Determinenecessitytostopindication__T05Printandsendconfirmationofreceipt
e 7 8  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 9 10  T05Printandsendconfirmationofreceipt__END
e 3 4  T06Determinenecessityofstopadvice__T07-4Draftinternaladvicetoholdfortype4
e 4 5  T07-4Draftinternaladvicetoholdfortype4__T06Determinenecessityofstopadvice

XP
v 1 START
v 2 Confirmationofreceipt
v 3 T02Checkconfirmationofreceipt
v 4 T04Determineconfirmationofreceipt
v 5 T05Printandsendconfirmationofreceipt
v 6 T06Determinenecessityofstopadvice
v 7 T07-4Draftinternaladvicetoholdfortype4
v 8 T06Determinenecessityofstopadvice
v 9 T10Determinenecessitytostopindication
v 10 END
e 1 2  START__Confirmationofreceipt
e 2 3  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 4  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 4 6  T04Determineconfirmationofreceipt__T06Determinenecessityofstopadvice
e 5 6  T05Printandsendconfirmationofreceipt__T06Determinenecessityofstopadvice
e 8 9  T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
e 9 10  T10Determinenecessitytostopindication__END
e 6 7  T06Determinenecessityofstopadvice__T07-4Draftinternaladvicetoholdfortype4
e 7 8  T07-4Draftinternaladvicetoholdfortype4__T06Determinenecessityofstopadvice

XP
v 1 START
v 2 Confirmationofreceipt
v 3 T02Checkconfirmationofreceipt
v 4 T04Determineconfirmationofreceipt
v 5 T06Determinenecessityofstopadvice
v 6 T05Printandsendconfirmationofreceipt
v 7 T10Determinenecessitytostopindication
v 8 T11CreatedocumentXrequestunlicensed
v 9 T12CheckdocumentXrequestunlicensed
v 10 T14DeterminedocumentXrequestunlicensed
v 11 T15PrintdocumentXrequestunlicensed
v 12 END
e 1 2  START__Confirmationofreceipt
e 2 3  Confirmationofreceipt__T02Checkconfirmationofreceipt
e 3 4  T02Checkconfirmationofreceipt__T04Determineconfirmationofreceipt
e 4 5  T04Determineconfirmationofreceipt__T06Determinenecessityofstopadvice
e 5 7  T06Determinenecessityofstopadvice__T10Determinenecessitytostopindication
e 6 7  T05Printandsendconfirmationofreceipt__T10Determinenecessitytostopindication
e 9 10  T12CheckdocumentXrequestunlicensed__T14DeterminedocumentXrequestunlicensed
e 10 11  T14DeterminedocumentXrequestunlicensed__T15PrintdocumentXrequestunlicensed
e 11 12  T15PrintdocumentXrequestunlicensed__END
e 7 8  T10Determinenecessitytostopindication__T11CreatedocumentXrequestunlicensed
e 8 9  T11CreatedocumentXrequestunlicensed__T12CheckdocumentXrequestunlicensed

